modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="${mod_issue_tracker_url}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
#    logoFile="creativecore.png"
    version="${mod_version}"
    displayName="${mod_name}
#    displayURL="https://modrinth.com/mod/creativecore"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
   modId="techcore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="${tech_core_version_range}"

[[mixins]]
   config="${mod_mixins}"